# Generated by Django 4.1.4 on 2022-12-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='oener',
            new_name='owner',
        ),
    ]
